### ISSUE TITLE
CAF::Service should allow to enable a service

### ISSUE THREAD

**Issue by jouvin** [quattor/CAF#133]
It's something we discussed a while ago at the time `CAF::Service` was started. But it was probably an issue/PR related to something else... `CAF::Service` is nice as it is abstracting the details on how to start/stop a service. But we are lacking the same for configuring the permanent state of a service, abstracting `chkconfig --level` on EL<7 and `systemctl enable` on EL7.
I remember from the old discussion that Luis (and probably a few others) were opposing adding this to `CAF::Service` saying that it was duplicating the feature of another configuration module with the risk that you have a "conflicting" configuration. I understand the point but I still disagree as we have some configuration modules (notably `dpmlfc` and `xrootd`) where the exact list of service to permanently enable is based on the configuration processing done by the configuration module and that doing it on the template site would require to reimplement part of this logic on the template side. So I'm still advocationg that such an addition would be very useful and the doc should make clear that you have the responsibility not to manage the same service through 2 different configuration modules (`chkconfig` and another one).
Lacking this feature had no practical effect so far but we the release of DPM under EL7, the current `ncm-dpmlfc` is broken as it doesn't manage the service correctly anymore...

**Comment by stdweird** [comment]
we can rediscuss this during the workshop, but i still do not see why `ncm-chkconfig` can't be used.
the components should configure the service they are meant to configure (this could mean briefly starting a service, but should also restore the service to its original state, i.e. stopping it in the end if it wasn't running before). the only component needed to actually enable services is ncm-chkconfig.
implementing the logic in pan is the preferred option imho, also because it is a lot easier typically (and less perl code :smile: )

what we do need however, is a `CAF::Service->status()` (and a `condrestart`), most of which can be found  https://github.com/quattor/configuration-modules-core/blob/master/ncm-postgresql/src/main/perl/Postgresql/Service.pm

if we would decide however that this is feature that components can handle, i think we should make this part of `CAF::Service->start` (or restart). i.e. any service started should be enabled automatically (or by default). (but removing the component should also imply disabling it, so some trivial unconfigure might required for each such component.

**Comment by jouvin** [comment]
I agree with you last paragraph: it should not be a distinct method but really an option of methods affecting the service state do do it permanently. I thought we already had the ` status` and `condrestart` methods, they are clearly needed.
I will try to have a look to see if I can offload the `chkconfig` part in `ncm-dpmlfc` to the template site without adding too much complexity to the templates (that are already quite large).

**Comment by stdweird** [comment]
status and espcially condrestart are not provided by all sysvinit services, so having it in CAF might imply that it doesn't work (and there's no easy way to query the init script to see if it is supported or not). also , i have no clue what the situation is in solaris.

**Comment by jrha** [comment]
As discussed at 21st workshop, we have decided that we will not implement this.
